package app

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	globalChainSelectGroupName = "节点选择"
	// globalChainRelayGroupName ("代理链") is no longer generated by
	// applyGlobalChainConfig -- global-chain mode moved to a dialer-proxy
	// chain instead of an explicit relay group -- but the name stays
	// reserved (and every error message mentioning it stays worded as
	// referring to a "generated global-chain group") for backward
	// compatibility with any already-saved instance whose LocalProxies or
	// profile config still uses this literal name; silently letting it
	// through now would be a behavior change for existing configs. L3
	// (docs/review-2026-07-11-testing-quality.md): the error text itself is
	// deliberately left unchanged here -- app.js's errorPatterns match it
	// verbatim -- this comment exists purely to explain why the wording
	// still says "generated" for a group that is, today, never actually
	// generated.
	globalChainRelayGroupName = "代理链"
)

// writeRuntimeConfig renders item's runtime mihomo config from profile's user
// config and writes it to item.RuntimeConfigPath. It also returns a shallow
// copy of the freshly parsed (but not yet cleaned/mutated) config map: L-6
// (docs/review-2026-07-11-go-concurrency-performance.md) -- the start path
// previously read and YAML-parsed profile.ConfigPath a second time just to
// compute configGeodataNeeds. Returning this snapshot here lets the caller
// reuse it instead. The copy is taken before cleanRuntimeConfig/
// applyGlobalChainConfig/applyRuntimeFields mutate cfg in place (global-chain
// mode in particular replaces "rules" entirely), so it reflects exactly what
// a second read-and-parse of profile.ConfigPath would have produced.
func writeRuntimeConfig(item *Instance, profile *Profile) (map[string]any, error) {
	raw, err := os.ReadFile(profile.ConfigPath)
	if err != nil {
		return nil, err
	}
	var cfg map[string]any
	if len(raw) == 0 {
		cfg = make(map[string]any)
	} else if err := yaml.Unmarshal(raw, &cfg); err != nil {
		return nil, fmt.Errorf("parse user config: %w", err)
	}
	if cfg == nil {
		cfg = make(map[string]any)
	}
	parsed := make(map[string]any, len(cfg))
	for key, value := range cfg {
		parsed[key] = value
	}

	cleanRuntimeConfig(cfg)
	if instanceMode(item.Mode) == InstanceModeGlobalChain {
		if err := applyGlobalChainConfig(cfg, item); err != nil {
			return nil, err
		}
	}
	if err := applyRuntimeFields(cfg, item); err != nil {
		return nil, err
	}

	out, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, err
	}
	// M4 (REVIEW-2026-07-04.md): this was the project's only non-atomic
	// config write -- os.WriteFile can leave a truncated file behind if the
	// process dies mid-write, which mihomo would then fail to start from.
	// writeFileAtomic (util.go) writes to a temp file in the same directory
	// and renames it into place, matching the 0600 permissions used here
	// before (same-user child process, no other principals need read access).
	if err := writeFileAtomic(item.RuntimeConfigPath, out, 0o600); err != nil {
		return nil, err
	}
	return parsed, nil
}

// cleanRuntimeConfig strips user-config keys that would otherwise let a
// hand-written or subscription config fight with the per-instance values
// applyRuntimeFields/applyProxyBindFields inject (port/listener addresses,
// the external-controller endpoint and its auth). dns.listen is
// deliberately NOT stripped here (arch M3,
// docs/review-2026-07-11-go-architecture.md): unlike the keys below, a fixed
// DNS listen address can be an intentional single-instance choice, so
// StartContext instead logs a warning (via configHasDNSListen) when it's
// present rather than silently dropping it -- the risk being that two
// instances sharing the same profile would then both try to bind it.
func cleanRuntimeConfig(cfg map[string]any) {
	for _, key := range []string{
		"port",
		"socks-port",
		"redir-port",
		"tproxy-port",
		"external-controller-tls",
		"external-controller-cors-allow-origins",
		"external-controller-unix",
		"external-controller-pipe",
		"external-ui",
		"external-ui-name",
		"external-ui-url",
		"listeners",
		"tun",
	} {
		delete(cfg, key)
	}
}

// configHasDNSListen reports whether cfg's "dns" section sets a "listen"
// address (arch M3). cfg should be the pre-mutation snapshot writeRuntimeConfig
// returns, though none of cleanRuntimeConfig/applyGlobalChainConfig/
// applyRuntimeFields touch the "dns" key either way.
func configHasDNSListen(cfg map[string]any) bool {
	dns, ok := cfg["dns"].(map[string]any)
	if !ok {
		return false
	}
	switch listen := dns["listen"].(type) {
	case string:
		return strings.TrimSpace(listen) != ""
	case nil:
		return false
	default:
		return true
	}
}

func applyRuntimeFields(cfg map[string]any, item *Instance) error {
	cfg["external-controller"] = fmt.Sprintf("127.0.0.1:%d", item.ControllerPort)
	cfg["secret"] = item.Secret
	return applyProxyBindFields(cfg, item)
}

func applyProxyBindFields(cfg map[string]any, item *Instance) error {
	addrs, err := parseProxyBindAddresses(item.ProxyBind)
	if err != nil {
		return err
	}
	if len(addrs) == 1 {
		cfg["mixed-port"] = item.MixedPort
		delete(cfg, "listeners")
		addr := addrs[0]
		if addr == defaultProxyBind {
			cfg["allow-lan"] = false
			cfg["bind-address"] = defaultProxyBind
			return nil
		}
		cfg["allow-lan"] = true
		cfg["bind-address"] = mihomoBindAddress(addr)
		return nil
	}

	delete(cfg, "mixed-port")
	delete(cfg, "bind-address")
	cfg["allow-lan"] = true
	listeners := make([]any, 0, len(addrs))
	for index, addr := range addrs {
		listeners = append(listeners, map[string]any{
			"name":   fmt.Sprintf("fleet-mixed-%d", index+1),
			"type":   "mixed",
			"port":   item.MixedPort,
			"listen": addr,
			"udp":    true,
		})
	}
	cfg["listeners"] = listeners
	return nil
}

func applyGlobalChainConfig(cfg map[string]any, item *Instance) error {
	proxies, inlineNames, err := proxyItemsAndNames(cfg["proxies"])
	if err != nil {
		return err
	}
	localProxies, localNames, err := parseLocalProxyItems(item.LocalProxies)
	if err != nil {
		return err
	}
	providerNames := proxyProviderNames(cfg["proxy-providers"])
	if len(inlineNames) == 0 && len(localNames) == 0 && len(providerNames) == 0 {
		return fmt.Errorf("global-chain mode requires proxies, proxy-providers, or local proxies")
	}

	for _, name := range inlineNames {
		if name == globalChainSelectGroupName || name == globalChainRelayGroupName {
			return fmt.Errorf("proxy name %q conflicts with generated global-chain group", name)
		}
	}
	inlineKnown := stringSet(inlineNames)
	for _, name := range localNames {
		if inlineKnown[name] {
			return fmt.Errorf("local proxy name %q conflicts with profile proxy", name)
		}
	}
	plan, err := buildGlobalChainPlan(item, inlineNames, localNames, providerNames)
	if err != nil {
		return err
	}

	for _, proxy := range localProxies {
		proxies = append(proxies, proxy)
	}
	applyDialerProxyChain(proxies, plan)
	if len(proxies) > 0 {
		cfg["proxies"] = proxies
	} else {
		delete(cfg, "proxies")
	}
	if plan.selectDialer != "" && len(providerNames) > 0 {
		applyProviderDialerProxy(cfg["proxy-providers"], plan.selectDialer)
	}

	selectGroup := map[string]any{
		"name": globalChainSelectGroupName,
		"type": "select",
	}
	if len(plan.selectNames) > 0 {
		selectGroup["proxies"] = plan.selectNames
	}
	if len(providerNames) > 0 {
		selectGroup["use"] = providerNames
	}

	cfg["mode"] = "rule"
	cfg["proxy-groups"] = []any{selectGroup}
	cfg["rules"] = []string{"NETWORK,UDP,REJECT", fmt.Sprintf("MATCH,%s", plan.matchTarget)}
	for _, key := range []string{"rule-providers", "sub-rules", "script"} {
		delete(cfg, key)
	}
	return nil
}

type globalChainPlan struct {
	chain        []string
	matchTarget  string
	proxyDialers map[string]string
	selectDialer string
	selectNames  []string
	usesSelect   bool
}

func buildGlobalChainPlan(item *Instance, inlineNames, localNames, providerNames []string) (globalChainPlan, error) {
	chain := normalizeChainNames(item.Chain)
	if len(chain) == 0 {
		chain = []string{globalChainSelectGroupName}
		if len(localNames) > 0 && (len(inlineNames) > 0 || len(providerNames) > 0) {
			chain = append(append([]string{}, localNames...), globalChainSelectGroupName)
		}
	}
	for _, name := range chain {
		if name == globalChainRelayGroupName {
			return globalChainPlan{}, fmt.Errorf("chain cannot reference generated relay group %q", name)
		}
	}

	proxyNames := stringSet(append(append([]string{}, inlineNames...), localNames...))
	seen := make(map[string]bool, len(chain))
	proxyDialers := make(map[string]string, len(chain))
	chainProxies := make(map[string]bool, len(chain))
	usesSelect := false
	for index, name := range chain {
		if seen[name] {
			return globalChainPlan{}, fmt.Errorf("chain contains duplicate member %q", name)
		}
		seen[name] = true
		if name == globalChainSelectGroupName {
			usesSelect = true
			continue
		}
		if !proxyNames[name] {
			return globalChainPlan{}, fmt.Errorf("chain references unknown proxy or group %q", name)
		}
		chainProxies[name] = true
		if index == 0 {
			proxyDialers[name] = ""
		}
	}

	selectDialer := ""
	for index := 1; index < len(chain); index++ {
		dialer := chain[index-1]
		name := chain[index]
		if name == globalChainSelectGroupName {
			selectDialer = dialer
			continue
		}
		proxyDialers[name] = dialer
	}

	selectNames := make([]string, 0, len(inlineNames)+len(localNames))
	for _, name := range append(append([]string{}, inlineNames...), localNames...) {
		if !usesSelect || !chainProxies[name] {
			selectNames = append(selectNames, name)
		}
	}
	selectNames = dedupeStrings(selectNames)
	if usesSelect && len(selectNames) == 0 && len(providerNames) == 0 {
		return globalChainPlan{}, fmt.Errorf("global-chain mode has no selectable proxy after chain members")
	}
	return globalChainPlan{
		chain:        chain,
		matchTarget:  chain[len(chain)-1],
		proxyDialers: proxyDialers,
		selectDialer: selectDialer,
		selectNames:  selectNames,
		usesSelect:   usesSelect,
	}, nil
}

func applyDialerProxyChain(proxies []any, plan globalChainPlan) {
	if len(plan.proxyDialers) == 0 && plan.selectDialer == "" {
		return
	}
	selectNames := stringSet(plan.selectNames)
	for _, item := range proxies {
		proxy, ok := item.(map[string]any)
		if !ok {
			continue
		}
		name := proxyName(item)
		if dialer, ok := plan.proxyDialers[name]; ok {
			if dialer == "" {
				delete(proxy, "dialer-proxy")
			} else {
				proxy["dialer-proxy"] = dialer
			}
			continue
		}
		if plan.selectDialer != "" && selectNames[name] {
			proxy["dialer-proxy"] = plan.selectDialer
		}
	}
}

func applyProviderDialerProxy(value any, dialer string) {
	providers, ok := value.(map[string]any)
	if !ok {
		return
	}
	for _, value := range providers {
		provider, ok := value.(map[string]any)
		if !ok {
			continue
		}
		override, _ := provider["override"].(map[string]any)
		if override == nil {
			override = make(map[string]any)
		}
		override["dialer-proxy"] = dialer
		provider["override"] = override
	}
}

func parseGlobalChainProxyGroups(config string, item *Instance) ([]ProfileProxyGroup, error) {
	var cfg map[string]any
	if err := yaml.Unmarshal([]byte(config), &cfg); err != nil {
		return nil, fmt.Errorf("parse profile config: %w", err)
	}
	if cfg == nil {
		cfg = make(map[string]any)
	}
	_, inlineNames, err := proxyItemsAndNames(cfg["proxies"])
	if err != nil {
		return nil, err
	}
	_, localNames, err := parseLocalProxyItems(item.LocalProxies)
	if err != nil {
		return nil, err
	}
	providerNames := proxyProviderNames(cfg["proxy-providers"])
	plan, err := buildGlobalChainPlan(item, inlineNames, localNames, providerNames)
	if err != nil {
		return nil, err
	}
	selections := normalizeSelections(item.SelectedProxies, item.SelectedGroup, item.SelectedProxy)
	group := ProfileProxyGroup{
		Name: globalChainSelectGroupName,
		Type: "select",
		All:  plan.selectNames,
		Now:  selectionForGroup(globalChainSelectGroupName, plan.selectNames, selections),
	}
	if len(providerNames) > 0 && len(plan.selectNames) == 0 {
		group.Now = ""
	}
	return []ProfileProxyGroup{group}, nil
}

func proxyItemsAndNames(value any) ([]any, []string, error) {
	if value == nil {
		return nil, nil, nil
	}
	items, ok := value.([]any)
	if !ok {
		return nil, nil, fmt.Errorf("proxies must be a list")
	}
	names := make([]string, 0, len(items))
	for _, item := range items {
		name := proxyName(item)
		if name == "" {
			continue
		}
		names = append(names, name)
	}
	return append([]any{}, items...), dedupeStrings(names), nil
}

func parseLocalProxyItems(raw string) ([]any, []string, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return nil, nil, nil
	}
	var parsed []map[string]any
	if err := yaml.Unmarshal([]byte(raw), &parsed); err != nil {
		// validationError preserves this exact "parse local proxies: ..."
		// text (matched by app.js's errorPatterns) while classifying as
		// errValidation instead of the substring-matching this used to rely
		// on (see former controller.go isInstanceValidationError).
		return nil, nil, validationError{msg: fmt.Sprintf("parse local proxies: %v", err)}
	}
	if len(parsed) == 0 {
		return nil, nil, nil
	}
	items := make([]any, 0, len(parsed))
	names := make([]string, 0, len(parsed))
	seen := make(map[string]bool, len(parsed))
	for index, item := range parsed {
		nameValue, ok := item["name"].(string)
		name := strings.TrimSpace(nameValue)
		if !ok || name == "" {
			return nil, nil, validationError{msg: fmt.Sprintf("local proxy %d is missing name", index+1)}
		}
		if seen[name] {
			return nil, nil, validationError{msg: fmt.Sprintf("local proxy name %q is duplicated", name)}
		}
		if name == globalChainSelectGroupName || name == globalChainRelayGroupName {
			return nil, nil, validationError{msg: fmt.Sprintf("local proxy name %q conflicts with generated global-chain group", name)}
		}
		item["name"] = name
		seen[name] = true
		items = append(items, item)
		names = append(names, name)
	}
	return items, names, nil
}

func proxyName(item any) string {
	proxy, ok := item.(map[string]any)
	if !ok {
		return ""
	}
	name, _ := proxy["name"].(string)
	return strings.TrimSpace(name)
}

func proxyProviderNames(value any) []string {
	providers, ok := value.(map[string]any)
	if !ok || len(providers) == 0 {
		return nil
	}
	names := make([]string, 0, len(providers))
	for name := range providers {
		if strings.TrimSpace(name) != "" {
			names = append(names, strings.TrimSpace(name))
		}
	}
	sort.Strings(names)
	return names
}

func normalizeChainNames(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		name := strings.TrimSpace(value)
		if name == "" {
			continue
		}
		out = append(out, name)
	}
	return out
}

func stringSet(values []string) map[string]bool {
	out := make(map[string]bool, len(values))
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			out[value] = true
		}
	}
	return out
}

func instanceMode(mode string) string {
	switch strings.TrimSpace(mode) {
	case "", InstanceModeRule:
		return InstanceModeRule
	case InstanceModeGlobalChain:
		return InstanceModeGlobalChain
	default:
		return InstanceModeRule
	}
}

func normalizeInstanceMode(mode string) (string, error) {
	switch strings.TrimSpace(mode) {
	case "", InstanceModeRule:
		return InstanceModeRule, nil
	case InstanceModeGlobalChain:
		return InstanceModeGlobalChain, nil
	default:
		return "", validationError{msg: fmt.Sprintf("instance mode %q is invalid", mode)}
	}
}
